### PR TITLE
Removed worthless error obfuscation

### PR DESCRIPTION
**Pull request by Sepero**
I've gotten this import error almost a dozen times before, and it has never once been because it "Can't find the file 'settings.py' in the directory".

Let's just print the real reason if it errors. We are all Python programmers here, so I would hope we all know how to read a real trace stack.

### CODE REVIEW

**Comment by georgedorn** [comment]
This is the manage.py that django 1.3.x (and probably others) generates.  This has nothing to do with django-nonrel.  I propose taking it up with the django project: https://github.com/django/django

**Comment by Sepero** [comment]
Here is the equivalent file in the 1.4 branch of the django project. https://github.com/django/django/blob/stable/1.4.x/django/conf/project_template/manage.py

We can see that it does not match the 1.4 branch testapp of django-nonrel. How should we proceed?

**Comment by aburgel** [comment]
testapp is very much based on the django 1.3 conventions. it hasn't really been updated for 1.4.

maybe the solution is to get rid of the testapp and create our an appengine specific 'project_template'. then the instructions for installing would be to download all the necessary files/apps and run createproject.

**Comment by Sepero** [comment]
I like the idea, but at the same time, I think we would agree that it's desirable to take anything that might we find beneficial from the parent project, and try to diverge only when necessary. It may be best to have someone look over the django project and see what, if anything from their project_template is worth salvaging.

**Comment by aburgel** [comment]
i think we would mirror the upstream's project_template and just add in any appengine specific files like app.yaml, queues.yaml, etc. maybe there is a way to do this so we don't have to mirror, more like inherit.

**Comment by Sepero** [comment]
Sounds good to me if it can be done.

**Pull request closed without merging**
